name: Install inno setup pkg

on: workflow_dispatch

jobs:

  install:

    runs-on: windows-latest

    steps:

      - name: Install inno setup package via chocolatey
        run: choco install innosetup

      - name: Check inno setup installation
        run: innosetup --version
        run: innosetup --help