name: Install inno setup pkg

on:
  push:
    branches:    
      - main

jobs:
  install:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
      - uses: actions/checkout@v2 
      - name: Install inno setup package via chocolatey
        run: choco install innosetup
      - name: Build setup
        run: iscc.exe setup\TcUnit.iss