name: Release TcUnit VsExtension setup 

on:
  push:
    branches:    
      - main

jobs:
  install:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install inno setup package via chocolatey
        run: choco install innosetup

      - name: Build setup
        run: iscc.exe setup\TcUnit.iss